spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: loan-route
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/v1/loans/**
          filters:
        #            - PrefixPath=/api/v1
        - id: identity-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
          # Uncomment if needed
          # - PrefixPath=/api/v1
          # - AddResponseHeader=X-powered-by,Maver Gateway Service

        - id: loan-service-swagger
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan-service/swagger-ui/**

        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui/**
      discovery:
        locator:
          enabled: true

  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/WalletAPI
          jwk-set-uri: http://localhost:9081/realms/WalletAPI/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
